// Layer management - MMGIS layer integration for workflow outputs

import * as Utils from './utils.js'
import * as API from './api.js'

// Group constants for workflow outputs
// Fixed RFC-format uuid — the Configure API's validator (uuidValidate)
// rejects human-readable ids and would regenerate them, breaking lookups.
export const GROUP_UUID = 'c7a4f1de-2f04-4e6b-9c8d-3b1a2e5f6a70'
export const GROUP_DISPLAY_NAME = 'Workflow Outputs'

/**
 * Ensures the "Workflow Outputs" header group exists in the layers tree
 * Creates it if missing, returns the existing one if present
 */
export function ensureWorkflowsGroup(L_) {
    if (L_.layers.data[GROUP_UUID]) return L_.layers.data[GROUP_UUID]
    const header = {
        // Post-parse convention: name IS the uuid (LayersTool builds DOM ids
        // from name; display_name carries the label).
        name: GROUP_UUID,
        uuid: GROUP_UUID,
        display_name: GROUP_DISPLAY_NAME,
        type: 'header',
        expanded: true,
        visibility: true,
        sublayers: [],
    }
    L_.layers.data[GROUP_UUID] = header
    L_.layers.nameToUUID = L_.layers.nameToUUID || {}
    L_.layers.nameToUUID[GROUP_DISPLAY_NAME] = [GROUP_UUID]
    L_.layers.on = L_.layers.on || {}
    L_.layers.on[GROUP_UUID] = true // headers always start on
    L_.layers.opacity = L_.layers.opacity || {}
    L_.layers.opacity[GROUP_UUID] = 1
    L_.layers.dataFlat = L_.layers.dataFlat || []
    L_.layers.dataFlat.unshift(header)
    L_.configData.layers = L_.configData.layers || []
    L_.configData.layers.unshift(header)
    return header
}

/**
 * Builds a markdown description for a job's layer
 * Used in the Layers panel Information modal
 */
export function buildLayerDescription(jobId, job) {
    const lines = ['Generated by the Workflows tool.', '']
    if (job.name) lines.push(`**Run:** ${job.name}`)
    lines.push(`**Workflow:** \`${jobId}\``)
    if (job.endpoint) lines.push(`**Endpoint:** \`${job.endpoint}\``)
    if (job.payload && Object.keys(job.payload).length > 0) {
        // TEMPORARY: file:// values stripped from display, same as the job
        // tiles (see comment on ENDPOINTS).
        const entries = Object.entries(job.payload).filter(
            ([, v]) => !Utils.isFilePathValue(v)
        )
        if (entries.length > 0) {
            lines.push('', '**Parameters:**', '')
            lines.push('| Parameter | Value |')
            lines.push('| --- | --- |')
            entries.forEach(([k, v]) => {
                lines.push(`| \`${k}\` | \`${v}\` |`)
            })
        }
    }
    return lines.join('\n')
}

/**
 * Builds an MMGIS layer object for a job output
 * Supports STAC items (tile layers) and vector outputs (geojson, etc.)
 */
export function buildLayerObjForJob(jobId, uri, job) {
    const uuid = jobId
    const base = {
        // MMGIS keys everything by uuid-as-name; display_name is the label.
        name: uuid,
        uuid,
        display_name: job.name || `Workflow ${jobId}`,
        description: buildLayerDescription(jobId, job),
        initialOpacity: 1,
        visibility: true,
        controlled: false,
        variables: {},
        // parseConfig stamps this on every layer; without it Map_ turns the
        // missing time into starttime/endtime of '' and the tile middleware
        // emits a `datetime=/` param that pgstac rejects.
        time: { enabled: false },
    }
    const stac = Utils.parseStacItemUrl(uri)
    if (stac) {
        // Piggy-back on MMGIS's stac-collection: handling — the workflow's
        // item lives in a per-user collection; adding the collection surfaces
        // the new item alongside any siblings via titilerpgstac tiles.
        return {
            ...base,
            type: 'tile',
            url: `stac-collection:${stac.collection}`,
            tileformat: 'wmts',
            minZoom: 0,
            // The config validator requires all three zoom fields on tile
            // layers (no defaults are filled for them).
            maxNativeZoom: 20,
            maxZoom: 20,
            style: {},
        }
    }
    // Vector: GeoJSON/GPKG/KML or WFS GetFeature returning JSON.
    return {
        ...base,
        type: 'vector',
        url: uri,
        style: {
            color: '#ff8800',
            fillColor: '#ff8800',
            fillOpacity: 0.5,
            weight: 2,
            radius: 6,
        },
    }
}

/**
 * Persists a layer into the mission's stored configuration
 * Tries to add to existing "Workflow Outputs" group, creates group if needed
 */
async function persistLayerToMission(layerObj, L_) {
    const mission = L_.mission
    if (!mission) return false
    const post = (body) =>
        API.mmgisFetch('api/configure/addLayer', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(body),
        })
            .then((r) => r.json())
            .catch(() => ({ status: 'failure', message: 'network error' }))

    let r = await post({
        mission,
        layer: layerObj,
        placement: { path: GROUP_DISPLAY_NAME, index: 0 },
    })
    if (r.status === 'success') return true
    if (!/not found/i.test(String(r.message || ''))) {
        console.warn('[MapJobSubmitTool] persist failed:', r.message, r.errors || r.badUUIDs || '')
        return false
    }
    r = await post({
        mission,
        layer: {
            name: GROUP_DISPLAY_NAME,
            uuid: GROUP_UUID,
            type: 'header',
            expanded: true,
            visibility: true,
            sublayers: [layerObj],
        },
        placement: { index: 0 },
    })
    if (r.status === 'success') return true
    console.warn('[MapJobSubmitTool] persist failed:', r.message, r.errors || r.badUUIDs || '')
    return false
}

/**
 * Removes a job's layer from the map and all registries
 * Also removes from stored mission config (best-effort)
 */
export async function removeLayerForJob(jobId, job, L_, ToolController_, renderJobsFn) {
    const layerObj = L_.layers.data[jobId]
    if (layerObj) {
        try {
            // Detach from the map first if currently visible.
            if (L_.layers.on[jobId] === true) {
                await L_.toggleLayer(layerObj, true)
            }
        } catch (err) {
            console.warn('[MapJobSubmitTool] layer detach failed', err)
        }
        delete L_.layers.layer[jobId]
        delete L_.layers.data[jobId]
        delete L_.layers.on[jobId]
        delete L_.layers.opacity[jobId]
        if (L_.layers.attachments) delete L_.layers.attachments[jobId]
        if (L_._layersParent) delete L_._layersParent[jobId]
        const oi = (L_._layersOrdered || []).indexOf(jobId)
        if (oi !== -1) L_._layersOrdered.splice(oi, 1)
        const fi = (L_.layers.dataFlat || []).findIndex(
            (l) => l && l.uuid === jobId
        )
        if (fi !== -1) L_.layers.dataFlat.splice(fi, 1)
        const dn = layerObj.display_name
        if (dn && L_.layers.nameToUUID && L_.layers.nameToUUID[dn]) {
            const ni = L_.layers.nameToUUID[dn].indexOf(jobId)
            if (ni !== -1) L_.layers.nameToUUID[dn].splice(ni, 1)
            if (L_.layers.nameToUUID[dn].length === 0)
                delete L_.layers.nameToUUID[dn]
        }
        // The group header object is shared with configData, so splicing its
        // sublayers updates the config tree too.
        const group = L_.layers.data[GROUP_UUID]
        if (group && Array.isArray(group.sublayers)) {
            const si = group.sublayers.findIndex(
                (l) => l && l.uuid === jobId
            )
            if (si !== -1) group.sublayers.splice(si, 1)
        }
        const layersTool = ToolController_.getTool
            ? ToolController_.getTool('LayersTool')
            : null
        if (
            ToolController_.activeToolName === 'LayersTool' &&
            layersTool &&
            layersTool.destroy &&
            layersTool.make
        ) {
            layersTool.destroy()
            layersTool.make()
        }
    }
    job.layerAdded = false
    job.persisted = undefined
    renderJobsFn()
    // Best-effort removal from the stored mission config; "not found" just
    // means it was session-only.
    API.mmgisFetch('api/configure/removeLayer', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ mission: L_.mission, layerUUID: jobId }),
    })
        .then((r) => r.json())
        .then((r) => {
            if (
                r.status !== 'success' &&
                !/not found|unable/i.test(String(r.message || ''))
            )
                console.warn(
                    '[MapJobSubmitTool] layer config removal:',
                    r.message
                )
        })
        .catch(() => {})
}

/**
 * Adds a layer to the map for a job's output
 * Creates layer, adds to group, renders on map, and persists to config
 */
export function addLayerForJob(jobId, job, L_, ToolController_, renderJobsFn) {
    const uri = job.autoAddableUri
    if (!uri) return
    const uuid = jobId
    const layerObj = buildLayerObjForJob(jobId, uri, job)
    // Skip mmgisAPI.addLayer (it forgets to re-parse the config) and skip the
    // resetConfig path (re-runs parseConfig over every existing mission layer,
    // surfacing unrelated latent bugs in those layers). Splice the new layer
    // directly into the already-parsed L_ registries — nested under the
    // shared "Workflows" header group — and ask the map to render only it.
    ;(async () => {
        try {
            if (L_.layers.data[uuid]) {
                // Already present; nothing to do.
                job.layerAdded = true
                renderJobsFn()
                return
            }
            const group = ensureWorkflowsGroup(L_)
            group.sublayers.unshift(layerObj)
            L_.layers.data[uuid] = layerObj
            L_.layers.nameToUUID = L_.layers.nameToUUID || {}
            L_.layers.nameToUUID[layerObj.display_name] =
                L_.layers.nameToUUID[layerObj.display_name] || []
            L_.layers.nameToUUID[layerObj.display_name].push(uuid)
            L_._layersOrdered = L_._layersOrdered || []
            L_._layersOrdered.unshift(uuid)
            L_.layers.dataFlat = L_.layers.dataFlat || []
            L_.layers.dataFlat.unshift(layerObj)
            L_.layers.on = L_.layers.on || {}
            L_.layers.on[uuid] = true
            L_.layers.opacity = L_.layers.opacity || {}
            L_.layers.opacity[uuid] = 1
            L_._layersParent = L_._layersParent || {}
            L_._layersParent[uuid] = GROUP_UUID
            await L_.Map_.makeLayer(layerObj, true)
            // makeLayer only constructs the Leaflet layer; addVisible is
            // what actually attaches it to the map (same two-step
            // addLayerToLayersData performs).
            L_.addVisible(L_.Map_, [uuid])
            // Refresh the Layers panel if it happens to be showing.
            const layersTool = ToolController_.getTool
                ? ToolController_.getTool('LayersTool')
                : null
            if (
                ToolController_.activeToolName === 'LayersTool' &&
                layersTool &&
                layersTool.destroy &&
                layersTool.make
            ) {
                layersTool.destroy()
                layersTool.make()
            }
            job.layerAdded = true
            job.persisted = 'pending'
            renderJobsFn()
            persistLayerToMission(layerObj, L_).then((ok) => {
                job.persisted = ok
                renderJobsFn()
            })
        } catch (err) {
            console.warn('[MapJobSubmitTool] addLayer failed', err)
        }
    })()
}
